server:
  port: 0
  servlet:
    context-path: /service-bus-broker
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
api:
  title: Message Broker Service Chassis Producer
  version: v1
  description: REST API Services for Message Broker Producer
spring:
  application:
    name: Message Broker Service Chassis Producer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
